name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.full.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: danielinux
          template: classic

          # Main summary block
          base: header, activity, repositories, metadata

          # Nice to have
          config_timezone: Europe/Rome

          # Intro section
          plugin_introduction: yes

          # Most used languages
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_details: bytes-size, percentage

          # Coding habits
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_charts: yes
          plugin_habits_facts: yes

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year


          # Recently starred repos
          plugin_stars: yes
          plugin_stars_limit: 4

          # Optional: featured repos block
          plugin_repositories: yes
